name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional release tag (e.g. v1.2.3). If omitted, workflow will generate one.'
        required: false
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Cache Gradle directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Determine tag name
        id: tag
        run: |
          # if tag provided via workflow_dispatch input, use it
          if [ -n "${{ github.event.inputs.tag || '' }}" ]; then
            TAG="${{ github.event.inputs.tag }}"
          # if this run is a tag push, use the tag name
          elif [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
            TAG="${BASH_REMATCH[1]}"
          # if run on main branch, generate a date-based tag
          elif [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            TAG="v$(date -u +'%Y.%m.%d')-r${GITHUB_RUN_NUMBER}"
          else
            TAG="v$(date -u +'%Y.%m.%d')-r${GITHUB_RUN_NUMBER}"
          fi
          echo "Computed tag: $TAG"
          echo "TAG_NAME=$TAG" >> $GITHUB_OUTPUT

      - name: Build (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon --stacktrace

      - name: Locate out/*.zip artifacts
        id: artifacts
        run: |
          set -e
          # List out directory if present
          ls -la out || true
          # Find zip files in out/ (adjust path if your project writes zips elsewhere)
          FILES=$(find out -maxdepth 1 -type f -name '*.zip' -print | tr '\n' ' ')
          if [ -z "$FILES" ]; then
            echo "files_found=false" >> $GITHUB_OUTPUT
            echo "files_list=" >> $GITHUB_OUTPUT
          else
            echo "files_found=true" >> $GITHUB_OUTPUT
            # Export a space-separated list usable by subsequent steps
            echo "files_list=$FILES" >> $GITHUB_OUTPUT
          fi

      - name: Fail if no out/*.zip found
        if: steps.artifacts.outputs.files_found != 'true'
        run: |
          echo "No out/*.zip artifact found. Ensure your build produces out/*.zip."
          exit 1

      - name: Create and push git tag
        env:
          TAG_NAME: ${{ steps.tag.outputs.TAG_NAME }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Create GitHub release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.TAG_NAME }}
          name: ${{ steps.tag.outputs.TAG_NAME }}
          body: "Automated release created by GitHub Actions for ${{ steps.tag.outputs.TAG_NAME }}"
          files: ${{ steps.artifacts.outputs.files_list }}
          draft: false
          prerelease: false
